apresentacao/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index')
]

meusite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apresentacao.urls'))
]

apresentacao/models.py
from django.db import models
from django import forms
from django.utils import timezone

class Usuario(models.Model):
    usuario = models.CharField(default='Anônimo', max_length=25)
    mensagem = models.CharField(max_length=120)
    data_da_mensagem = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.usuario


class FormUsuario(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = ('data_da_mensagem',)

apresentacao/views.py
from django.shortcuts import render, redirect
from .models import Usuario, FormUsuario


def index(request):
    dados = Usuario.objects.all()
    form = FormUsuario()
    if request.method != 'POST':
        return render(request, 'paginas/index.html',{
            'mensagens': dados,
            'usuario': form
        })
    
    form = FormUsuario(request.POST)
    if form.is_valid:
        form.save()
    return redirect('index')

apresentacao/templates/paginas/index.html
{%extends 'base.html'%}
{% load static %}
{%block 'titulo'%} Pagina Principal {%endblock%}

{%block 'conteudo'%}
    <header>
        <h1>MARCELO</h1>
    </header>

    <div id="conteudo">
        <span>
            <div id="sobre">
                <h2>sobre mim</h2>
                <p class="descricao">
                    Me chamo Marcelo
                    tenho 22 anos, de São Luís-MA
                    <br>
                    No 3º periodo de Redes de Computadores no IFMA-São João dos Patos
                    <br>
                    Possuo conhecimentos em Python, MySQL e me aventuro no front-end
                </p>
                     
            </div>
            <img id="l1" src="{% static 'imagens/Lgif.gif' %}" alt="">
        </span>     
        
        <span>
            <div id="projetos">
                <h2>projetos</h2>
                <p class="descricao">
                    Ando fazendo uns projetos médio solo
                    (nada postado no repositorio ainda)
                    mas se quiser da uma olhada nos meus projetos pequenos que fiz usando apenas Python
                    <a class="links" target="_blank" rel="external" href="https://github.com/marcelo-py">segue o link</a>
                    <span style="margin-top: 10px;">uma livraria que fiz usando Django, HTML e CSS <a class="links" href="https://donos-do-livro.herokuapp.com">donos-do-livro.herokuapp.com</a></span>
                </p>
            </div>
            <img id="l2" src="{% static 'imagens/morcegobatman.gif' %}" alt="">
        </span>

        <span>
            <div id="contatos">
                <h2>contatos</h2>
                <a class="contato_link" href="https://www.facebook.com/marcelo.jovi.7"><img class="contatos" src="{% static 'imagens/facebook_icone.png' %}" alt=""></a>
                <a class="contato_link" href="https://www.instagram.com/marcell0.o"><img class="contatos" src="{% static 'imagens/insta_icone.png' %}" alt=""></a>
                <a class="contato_link" href="https://github.com/marcelo-py"><img class="contatos" src="{% static 'imagens/github_icone.png'%}" alt=""></a>      
            </div>
            <img id="l3" src="{% static 'imagens/Lgif.gif' %}" alt="">
        </span>
        <div id="mensagens">
            <h2 id="h2damensagem">mensagens anônimas</h2>
            {%for mensagem in mensagens%}
                {% if mensagem.mensagem %}
                    <p id="mensage">
                        <b>{{ mensagem.usuario }}:</b>
                        <code>{{ mensagem.mensagem }}
                            <span id="data">({{ mensagem.data_da_mensagem|date:'d/m/Y' }})</span>  
                        </code> 
                    </p>
                {%endif%}
            {%endfor%}       
        </div>

        <div class="coisasdamsg">
            <form id="mandamsg" action="{% url 'index' %}" method="post">
                {% csrf_token %}
                {{ usuario }}
                <button type="submit">Enviar</button>
            </form>
        </div>
        
    </div>
    
{%endblock%}

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    {%include 'parciais/head.html'%}
    <title>{%block 'titulo'%}{%endblock%}</title>
    <style>
        @font-face{
            font-family: 'Dripping';
            src: url("{% static 'fonts/Pixel Emulator.otf' %}")
            format('opentype');
            font-weight: 0px;
        }
        @font-face {
            font-family: 'start';
            src: url("{% static 'fonts/PressStart2P-Regular.ttf' %}")
            format('truetype');
            font-weight: normal;
        }
        * {
            margin: 0;
            padding: 0;
        }
        header{
            margin-top: 1%;
        }
        body{
            background-image: linear-gradient(45deg, #b55fee, rgb(156, 38, 156), #892CDC, #52057B);
            background-size: 1050% 1050%;
            animation: cores 15s ease-in infinite;
            width: 100%;
            height: 100%;
            /*url("{%static 'imagens/imagem_do_fundo.jpg' %}");*/
        }
        h1{
            font-family: 'Dripping';
            margin: 0 0 0 10px;
            font-size: 70px;
            display: inline-block;
            color: rgb(36, 5, 36);
            text-shadow: 1px 1px 1px rgba(181, 131, 201, 0.884);
        }
        #sobre, #projetos, #contatos{
            box-shadow: 2px 2px 3px rgba(100, 69, 114, 0.671);
            width: 330px;
            height: 300px;        
            margin: 9px;
            border-radius: 15px;
            text-align: center;
            overflow: hidden;
        }
        h2{
            text-align: center;
            font-size: 18px;
            font-family: 'start';
            margin: 5px;
        }
        #conteudo{
            text-align: center;
        }

        #sobre, #contatos{
            background-color: #43314dd3;
        }
        #projetos{
            background-color: #3b1c49ad;
        }
        .descricao{
            font-family:'Courier New', Courier, monospace;
            word-wrap: break-word;
            font-size: 18px;
            text-align: justify;
            text-indent: 10px;
            margin-top: 5%;
            margin-left: 3%;
            margin-right: 3%;
            text-shadow: 0 0 0.7px black;
            
        }
        span{
            display: inline-block;
        }
        
        #l1, #l2, #l3 {
            width: 120px;
            height: 120px;
        }

        span > #l1{
            display: none;
        }
        span > #l2{
            display: none;
        }
        span > #l3{
            display: none;
        }
 
        span:hover > #l1{
            display: inline-block;
        }
        span:hover > #l2{
            display: inline-block;
        }
        span:hover > #l3{
            display: inline-block;
        }
        #mensagens{
            background-color: #1e032ce3;
            width: 300px;
            max-height: 430px;
            display: inline-block;
            overflow-y: scroll;
            margin: 9px;
            position: relative;
        }
        #mensage{
            word-wrap: break-word;
            color: green;
            box-shadow: 0 0 6px rgb(10, 1, 12);
            text-align: justify;
            font-size: 17px;
            padding: 3%;
        }
        .links{
            text-decoration: none;
            color: rgb(0, 89, 255);
        }
        .contatos{
            width: 50px;
            height: 50px;
            margin: 10px;
        }
        .contato_link{
            display: inline;
        }

        label{
            margin-left: 50%;
        }
        input{
            width: 315px;;
        }
        .coisasdamsg{
            text-align: right;
        }
        button{
            width: 50px;
            height: 30px;
            font-size: 15px;
            position: relative;
            display: flow-root;
            left: 87%;
        }

        #id_usuario{
            width: 120px;
        }
        #data{
            color: rgba(240, 255, 255, 0.596);
            font-size: 11px;
            display: flex;
        }
        @keyframes cores{
            0%{
               background-position: 0% 50%;
            }
            50%{
                background-position: 100% 50%;
            }
            100%{
                background-position: 0% 50%;
            }
        }
        @media (min-width: 100px) and (max-width: 579px) {
            h1{
                font-size: 17vw;
            }
        }
        @media (min-width: 50px) and (max-width: 900px){
            #projetos, #contatos, #sobre{
                width: 90vw;
                height: auto;
            }
            #projetos{
                height: auto;
            }
            #mensagens{
                width: 90vw;
                max-height: 900px;

            }
            h2{
                font-size: 9vw;
            }
            .descricao{
                font-size: 20px;
                width: 95%;
                word-wrap: break-word;
            }
            #mensage{
                font-size: 9vw;
            }

            address{
                font-size: 5vw;
            }
            .contatos{
                width: 15vw;
                height: 15vw;
            }
            h1{
                margin-top: 2%;
            }
            .coisasdamsg{
                text-align: center;
            }
            #mandamsg{
                width: 90%;
                margin: 0%;
            }
            label{
                margin-left: 0%;
                margin-left: 20%;
                font-size: 9vw;
                margin: 0%;
            }
            input{
                font-size: 7vw;
                width: 80vw;
                margin: 0%;
            }
            button{
                width: 20vw;
                height: 10vw;
                font-size: 6vw;
                position: relative;
                left: 50%;
            }
            #id_usuario{
                width: 50vw;
            }
            header{
                margin-top: 3%;
            }
            #data{
                font-size: 20px;
            }
        }
    </style>
</head>

<body>
    {%block 'conteudo'%}
    {%endblock%}
</body>
</html>

templates/parciais/head.html
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">